name: Haxe Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: haxe:4.3.4
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Haxe Build
        run: haxe build.hxml
